services:
  - type: web
    name: gme-ultimate-tracker
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -b 0.0.0.0:$PORT
